name: collegram
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - jupyter_server
  - msgspec
  - polars
  - matplotlib
  - pip:
    # local package
    - -e .
    # external requirements
    - python-dotenv>=0.5.1
    - tqdm
    - telethon
    # For faster media DL:
    - cryptg
    - lingua-language-detector
