name: collegram
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - jupyter_server
  - matplotlib
  - scipy
  - pip:
    # local package
    - -e .
    # For faster media DL:
    - cryptg
    - git+https://github.com/TLouf/plots.git
